title: Albert Chenag personal page
page-top-title: Cheang Chi Hou 
top-section-bg-text: Computer Science
home-subtitle: Cheang Chi Hou&ensp;|&ensp;鄭子浩
copyright-text: '&copy; Cheang Chi Hou 2025-2029. All Rights Reserved.'
